spring:
  application:
    name: gulimall-thrid-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud: #阿里云对象存储服务
      secret-key: 
      access-key: 
      oss:
        endpoint: 
  smssend: # 短信验证码配置
    host: 
    path: /sms/smsSend
    templateid: 
    appcode: 
    sms-sign-id: 
server:
  port: 12000


